spring.application.name=task-management
server.port=8081

app.jwt.secret=xJ5vY8wZq3rT6uI9oP2aS5dF8gH1jK4lM7nB0vC3xZ6qW9eR2tY5uI8oP1aS4dF7g
app.jwt.expiration-ms=18000000

spring.datasource.url=jdbc:postgresql://localhost:5432/task_management_db
spring.datasource.username=postgres
spring.datasource.password=140506

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect